#' @importFrom dplyr across
#' @importFrom dplyr arrange
#' @importFrom dplyr anti_join
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_match
#' @importFrom dplyr case_when
#' @importFrom dplyr distinct
#' @importFrom dplyr enframe
#' @importFrom dplyr filter
#' @importFrom dplyr first
#' @importFrom dplyr full_join
#' @importFrom dplyr group_by
#' @importFrom dplyr if_else
#' @importFrom dplyr intersect
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr pull
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr right_join
#' @importFrom dplyr row_number
#' @importFrom dplyr rowwise
#' @importFrom dplyr select
#' @importFrom dplyr setdiff
#' @importFrom dplyr summarize
#' @importFrom dplyr ungroup
#' @importFrom heatmaply heatmaply
#' @importFrom htmltools div
#' @importFrom htmltools span
#' @importFrom htmlwidgets JS
#' @importFrom htmlwidgets saveWidget
#' @importFrom kinship2 kinship
#' @importFrom lubridate as.numeric
#' @importFrom lubridate as.period
#' @importFrom lubridate ceiling_date
#' @importFrom lubridate floor_date
#' @importFrom lubridate interval
#' @importFrom pedtools ancestors
#' @importFrom pedtools children
#' @importFrom pedtools commonDescendants
#' @importFrom pedtools descendants
#' @importFrom pedtools descentPaths
#' @importFrom pedtools females
#' @importFrom pedtools founders
#' @importFrom pedtools generations
#' @importFrom pedtools leaves
#' @importFrom pedtools nonfounders
#' @importFrom pedtools males
#' @importFrom pedtools parents
#' @importFrom pedtools ped
#' @importFrom pedtools plot.ped
#' @importFrom pedtools siblings
#' @importFrom pedtools unrelated
#' @importFrom plotly add_trace
#' @importFrom plotly layout
#' @importFrom plotly plot_ly
#' @importFrom purrr compact
#' @importFrom purrr keep
#' @importFrom purrr keep_at
#' @importFrom purrr list_assign
#' @importFrom purrr list_flatten
#' @importFrom purrr imap
#' @importFrom purrr map
#' @importFrom purrr map2
#' @importFrom purrr map_dbl
#' @importFrom purrr map_depth
#' @importFrom purrr pmap
#' @importFrom reactable reactable
#' @importFrom reactable colDef
#' @importFrom reactable colFormat
#' @importFrom reactable colGroup
#' @importFrom reactablefmtr bubble_grid
#' @importFrom reactablefmtr color_tiles
#' @importFrom reactablefmtr data_bars
#' @importFrom reactablefmtr flatly
#' @importFrom reactablefmtr pill_buttons
#' @importFrom ribd inbreeding
#' @importFrom rlang set_names
#' @importFrom paletteer paletteer_d
#' @importFrom scales label_date
#' @importFrom scales label_percent
#' @importFrom scales label_number
#' @importFrom stats setNames
#' @importFrom stringr str_glue
#' @importFrom stringr str_remove_all
#' @importFrom tibble tibble
#' @importFrom tidyr expand_grid
#' @importFrom tidyr fill
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr replace_na
#' @importFrom tidyr unnest
#' @importFrom tidyr unnest_longer
#' @importFrom tidyr unnest_wider
#' @importFrom tidyselect everything
#' @importFrom tidyselect ends_with
#' @importFrom tidyselect starts_with
#' @importFrom tidyselect where
#' @importFrom tippy tippy
#' @importFrom verbalisr verbalise
#' @importFrom visNetwork addFontAwesome
#' @importFrom visNetwork visInteraction
#' @importFrom visNetwork visLegend
#' @importFrom visNetwork visNetwork
#' @importFrom visNetwork visNodes
#' @importFrom visNetwork visSave

